export type SystemRole = 'ADMINISTRADOR' | 'USUARIO'
export type UserStatus = 'ACTIVO' | 'INACTIVO'
export type GroupRole = 'LIDER' | 'EDITOR'
export type DefaultView = 'CURRENT_PLAN' | 'MY_GROUPS' | 'USER_MANAGEMENT' | 'GROUP_MANAGEMENT'

export type PetiPhase = 'IDENTITY' | 'DIAGNOSTICS' | 'FORMULATION' | 'CONSOLIDATION'
export type PhaseChangeStatus = 'DRAFT' | 'PENDING_APPROVAL' | 'APPROVED' | 'REJECTED'
export type DiagnosticPriority = 'BAJA' | 'MEDIA' | 'ALTA'
export type SwotCategory = 'FORTALEZA' | 'OPORTUNIDAD' | 'DEBILIDAD' | 'AMENAZA'
export type ValueChainActivityType = 'APOYO' | 'PRIMARIA'
export type ValueChainActivity =
  | 'INFRAESTRUCTURA_EMPRESARIAL'
  | 'GESTION_RECURSOS_HUMANOS'
  | 'COMPRAS'
  | 'DESARROLLO_TECNOLOGICO'
  | 'LOGISTICA_ENTRADA'
  | 'OPERACIONES'
  | 'LOGISTICA_SALIDA'
  | 'MARKETING_VENTAS'
  | 'SERVICIOS'
export type BcgQuadrant = 'ESTRELLA' | 'INCOGNITA' | 'VACA' | 'PERRO'
export type BcgStrategicDecision = 'POTENCIAR' | 'EVALUAR' | 'MANTENER' | 'REESTRUCTURAR_O_DESINVERTIR'
export type PestFactor = 'SOCIAL_DEMOGRAPHIC' | 'ENVIRONMENTAL' | 'POLITICAL' | 'ECONOMIC' | 'TECHNOLOGICAL'
export type PorterForce = 'INDUSTRY_RIVALRY' | 'NEW_ENTRANTS' | 'BUYER_POWER' | 'SUPPLIER_POWER' | 'SUBSTITUTES'
export type ValueChainDimension =
  | 'PROCESS_NORMALIZATION'
  | 'TECHNOLOGY_IMPROVEMENT'
  | 'PRODUCT_PRODUCTIVITY'
  | 'ORGANIZATION_STRATEGY'
  | 'CUSTOMER_DISTRIBUTION'
